import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class SasiStatusService {

  constructor() { }

  getSasiStatusTime(): Observable<any[]> {
    const data = [
      {
        propertyName: 'Base Time',
        purgatoryTime: '2015-03-18 11:10Z',
        paradiseTime: '2015-03-18 11:10Z',
        published_0_Time: '2015-03-18 11:10Z',
        published_1_Time: '2015-03-18 11:10Z',
        published_2_Time: '2018-08-14 07:24Z',
        qSize: `<span class="span-width-3v"><b>Q size</b></span><span class="span-width-3v">0</span>
                <span class="span-width-3v"><b>Q ms</b></span><span class="span-width-3v">0</span>`
      },
      {
        propertyName: 'Last Data Update Time',
        purgatoryTime: '2018-07-30 09:07Z',
        paradiseTime: '2018-08-14 07:24Z',
        published_0_Time: '2018-08-14 07:24Z',
        published_1_Time: '2018-08-14 07:24Z',
        published_2_Time: '2018-08-14 07:24Z',
        qSize: `<span class="span-width-3v"><b>max</b></span><span class="span-width-3v">100</span>
                <span class="span-width-3v"><b>max</b></span><span class="span-width-3v">0</span>`
      },
      {
        propertyName: 'Latest Flight Actual Time',
        purgatoryTime: '0',
        paradiseTime: '0',
        published_0_Time: '0',
        published_1_Time: '0',
        published_2_Time: '0',
        qSize: `<span class="span-width-3v"><b>min</b></span><span class="span-width-3v">0</span>
                <span class="span-width-3v"><b>min</b></span><span class="span-width-3v">0</span>`
      }
    ];
    return of(data);
  }

  getSasiStatusWorldObjects(): Observable<any[]> {
    const data = [
      {
        propertyName: 'Total',
        purgatoryEvents: '-',
        purgatoryObj: '27658',
        validationIEPM: '-',
        validationExcl: '1304',
        validationFixed: '914',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '26354',
        published_0_Events: '-',
        published_0_Obj: '26354',
        published_1_Events: '-',
        published_1_Obj: '145551',
        published_2_Events: '-',
        published_2_Obj: '618'
      },
      {
        propertyName: 'Δ from previous world',
        purgatoryEvents: '',
        purgatoryObj: '',
        validationIEPM: '',
        validationExcl: '',
        validationFixed: '',
        validationOEPM: '',
        paradiseEvents: '-',
        paradiseObj: '1304',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '-',
        published_1_Obj: '-119197',
        published_2_Events: '-',
        published_2_Obj: '144933'
      },
      {
        propertyName: 'Aircraft',
        purgatoryEvents: '-',
        purgatoryObj: '203',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '203',
        published_0_Events: '-',
        published_0_Obj: '203',
        published_1_Events: '-',
        published_1_Obj: '967',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Airport',
        purgatoryEvents: '-',
        purgatoryObj: '414',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '414',
        published_0_Events: '-',
        published_0_Obj: '414',
        published_1_Events: '-',
        published_1_Obj: '546',
        published_2_Events: '-',
        published_2_Obj: '1'
      },
      {
        propertyName: 'AirportGroup',
        purgatoryEvents: '-',
        purgatoryObj: '7',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '7',
        published_0_Events: '-',
        published_0_Obj: '7',
        published_1_Events: '-',
        published_1_Obj: '4',
        published_2_Events: '-',
        published_2_Obj: '24'
      },
      {
        propertyName: 'AirportGroupRelationship',
        purgatoryEvents: '-',
        purgatoryObj: '7',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '7',
        published_0_Events: '-',
        published_0_Obj: '7',
        published_1_Events: '-',
        published_1_Obj: '4',
        published_2_Events: '-',
        published_2_Obj: '24'
      },
      {
        propertyName: 'ATCControlledStation',
        purgatoryEvents: '-',
        purgatoryObj: '-',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '-',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Crew',
        purgatoryEvents: '-',
        purgatoryObj: '6373',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '914',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '6373',
        published_0_Events: '-',
        published_0_Obj: '6373',
        published_1_Events: '-',
        published_1_Obj: '25815',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'CrewBase',
        purgatoryEvents: '-',
        purgatoryObj: '6',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '6',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '6',
        published_0_Events: '-',
        published_0_Obj: '6',
        published_1_Events: '-',
        published_1_Obj: '12',
        published_2_Events: '-',
        published_2_Obj: '1'
      },
      {
        propertyName: 'Fleet',
        purgatoryEvents: '-',
        purgatoryObj: '4',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '4',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '4',
        published_0_Events: '-',
        published_0_Obj: '4',
        published_1_Events: '-',
        published_1_Obj: '1',
        published_2_Events: '-',
        published_2_Obj: '2'
      },
      {
        propertyName: 'FleetCompatibility',
        purgatoryEvents: '-',
        purgatoryObj: '12',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '12',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '12',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '6'
      },
      {
        propertyName: 'Flight',
        purgatoryEvents: '-',
        purgatoryObj: '12057',
        validationIEPM: '-',
        validationExcl: '810',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '12247',
        published_0_Events: '-',
        published_0_Obj: '12247',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '85367',
        published_2_Obj: '-'
      },
      {
        propertyName: 'FlightActivity',
        purgatoryEvents: '-',
        purgatoryObj: '1',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '1',
        published_0_Events: '-',
        published_0_Obj: '1',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '1'
      },
      {
        propertyName: 'InterSegmentTime',
        purgatoryEvents: '-',
        purgatoryObj: '-',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '-',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '20',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Maintenance',
        purgatoryEvents: '-',
        purgatoryObj: '856',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '856',
        published_0_Events: '-',
        published_0_Obj: '856',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Market',
        purgatoryEvents: '-',
        purgatoryObj: '-',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '-',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'NonFly',
        purgatoryEvents: '-',
        purgatoryObj: '-',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '-',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '-',
        published_1_Obj: '215',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'OfflineTransportations',
        purgatoryEvents: '-',
        purgatoryObj: '595',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '595',
        published_0_Events: '-',
        published_0_Obj: '595',
        published_1_Events: '-',
        published_1_Obj: '1239',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Pairing',
        purgatoryEvents: '-',
        purgatoryObj: '5899',
        validationIEPM: '-',
        validationExcl: '494',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '5405',
        published_0_Events: '-',
        published_0_Obj: '5405',
        published_1_Events: '-',
        published_1_Obj: '31294',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'PassengerConnection',
        purgatoryEvents: '-',
        purgatoryObj: '-',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '-',
        published_0_Events: '-',
        published_0_Obj: '-',
        published_1_Events: '-',
        published_1_Obj: '-',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Position',
        purgatoryEvents: '-',
        purgatoryObj: '3',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '3',
        published_0_Events: '-',
        published_0_Obj: '3',
        published_1_Events: '-',
        published_1_Obj: '3',
        published_2_Events: '-',
        published_2_Obj: '4'
      },
      {
        propertyName: 'Qualification',
        purgatoryEvents: '-',
        purgatoryObj: '164',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '164',
        published_0_Events: '-',
        published_0_Obj: '164',
        published_1_Events: '-',
        published_1_Obj: '31',
        published_2_Events: '-',
        published_2_Obj: '-'
      },
      {
        propertyName: 'Subfleet',
        purgatoryEvents: '-',
        purgatoryObj: '7',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '7',
        published_0_Events: '-',
        published_0_Obj: '7',
        published_1_Events: '-',
        published_1_Obj: '19',
        published_2_Events: '-',
        published_2_Obj: '3'
      },
      {
        propertyName: 'Training',
        purgatoryEvents: '-',
        purgatoryObj: '8',
        validationIEPM: '-',
        validationExcl: '-',
        validationFixed: '-',
        validationOEPM: '-',
        paradiseEvents: '-',
        paradiseObj: '8',
        published_0_Events: '-',
        published_0_Obj: '8',
        published_1_Events: '-',
        published_1_Obj: '5',
        published_2_Events: '-',
        published_2_Obj: '-'
      }
    ];
    return of(data);
  }
}
